### ISSUE TITLE
SSL Get Request: 406 Not Acceptable in RestClient; Works in Net::HTTP and curl

### ISSUE THREAD

**Issue by Flauschbaellchen** [rest-client/rest-client#283]
Hi,

I'm currently trying to access an API through SSL using the code from the Readme:

``` ruby
facts = RestClient::Resource.new(
        'https://example.com:8081/v3/nodes/intranet.example.com/facts',
        :ssl_client_cert  =>  OpenSSL::X509::Certificate.new(File.read("cert.pem")),
        :ssl_client_key   =>  OpenSSL::PKey::RSA.new(File.read("key.pem")),
        :ssl_ca_file      =>  "ca_certificate.pem",
        :verify_ssl       =>  OpenSSL::SSL::VERIFY_NONE
      ).get
```

The result is the following error:

```
RestClient::NotAcceptable: 406 Not Acceptable
        from /nethome/intranet/www/intranet/shared/bundle/ruby/2.1.0/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!'
        from /nethome/intranet/www/intranet/shared/bundle/ruby/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:230:in `process_result'
        from /nethome/intranet/www/intranet/shared/bundle/ruby/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:178:in `block in transmit'
        from /usr/local/rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/net/http.rb:853:in `start'
        from /nethome/intranet/www/intranet/shared/bundle/ruby/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
        from /nethome/intranet/www/intranet/shared/bundle/ruby/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
        from /nethome/intranet/www/intranet/shared/bundle/ruby/2.1.0/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
        from /nethome/intranet/www/intranet/shared/bundle/ruby/2.1.0/gems/rest-client-1.6.7/lib/restclient/resource.rb:51:in `get'
        from (irb):93
...
```

Most likely it's a server error, but because I couldn't find anything, I tried with curl and the blank Net::HTTP:

```
curl 'https://example.com:8081/v3/nodes/intranet.example.com/facts' --cacert ca_certificate.pem --key key.pem --cert cert.pem
```

``` ruby
uri = URI.parse("https://example.com:8081/v3/nodes/intranet.example.com/facts")
http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true
http.cert = OpenSSL::X509::Certificate.new(File.read("cert.pem"))
http.key = OpenSSL::PKey::RSA.new(File.read("key.pem"))
http.verify_mode = OpenSSL::SSL::VERIFY_NONE
request = Net::HTTP::Get.new(uri.request_uri)
```

curl as well as Net::HTTP are working and are returning the desired content.
Is this a bug in RestClient; any more options/attributes which need to be set?

Versions:
rest-client-1.6.7
ruby 2.1.0p0
curl 7.26.0
puppetmaster 3.5.1 (for completeness)

Thanks in advance!

**Comment by kironiitdu** [comment]
I have resolved the issue using following way:

```
            HttpClientHandler clientHandler = new HttpClientHandler();
            clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };

            HttpClient httpClient = new HttpClient(clientHandler);
            httpClient.BaseAddress = new Uri("https://localhost:44361/");

            var restClient = new RestClient(httpClient);
            var request = new RestRequest("UserLog/GetData", Method.Get) { RequestFormat = DataFormat.Json };
            var response = restClient.Execute<List<QueryExecutionModel>>(request);
```
