### ISSUE TITLE
Reponse string  Marshal.dump error

### ISSUE THREAD

**Issue by Able1991** [rest-client/rest-client#370]
I have REST service which returns a html [string](https://gist.github.com/Able1991/2318db3f8f44498b45c4), I write this in the rails cache
This is my code
```ruby
 response = RestClient.post DocView + "files/" + rguid + '/print', {:format => 'xhtml', :data => source.to_json}
 Rails.cache.write("#{key}", response)
```
When i use latest version of RestClient(1.8.0) a have an error
```
no _dump_data is defined for class StringIO
activesupport (3.2.13) lib/active_support/cache.rb:561:in `dump'
activesupport (3.2.13) lib/active_support/cache.rb:561:in `initialize'
activesupport (3.2.13) lib/active_support/cache.rb:363:in `new'
activesupport (3.2.13) lib/active_support/cache.rb:363:in `block in write'
activesupport (3.2.13) lib/active_support/cache.rb:520:in `instrument'
activesupport (3.2.13) lib/active_support/cache.rb:362:in `write'
app/controllers/print_controller.rb:546:in `generate_document'
actionpack (3.2.13) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.13) lib/abstract_controller/base.rb:167:in `process_action'
```
If I change the version of the client on 1.7.3 the error disappears

**Comment by ab** [comment]
Ugh. This is an unfortunate consequence of AbstractResponse being mixed into the response String object. (It's a terrible design, but one that we're stuck with until a new major release.)

If you actually just want the response string (and not headers or other data), you should be able to work around this by saving `String.new(response)` instead.

**Comment by manuelmeurer** [comment]
I get a similar error after updating to 1.8.0:

```
Exception: TypeError: no _dump_data is defined for class OpenSSL::X509::Store
--
 0: /Users/manuel/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `dump'
 1: /Users/manuel/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:29:in `_marshal'
 2: /Users/manuel/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-store-1.1.4/lib/redis/store/marshalling.rb:5:in `set'
 3: /Users/manuel/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:5:in `block in set'
 4: /Users/manuel/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:50:in `namespace'
 5: /Users/manuel/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-store-1.1.4/lib/redis/store/namespace.rb:5:in `set'
 6: /Users/manuel/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:163:in `write_entry'
 7: /Users/manuel/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:36:in `block in write'
 8: /Users/manuel/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.10/lib/active_support/cache.rb:548:in `instrument'
 9: /Users/manuel/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/redis-activesupport-4.0.0/lib/active_support/cache/redis_store.rb:34:in `write'
10: /Users/manuel/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.10/lib/active_support/cache.rb:590:in `save_block_result_to_cache'
11: /Users/manuel/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.1.10/lib/active_support/cache.rb:296:in `fetch'
```

Why did this not happen in versions before 1.8.0?
Can this somehow be fixed before 2.0?
Cheers!

**Comment by ab** [comment]
@manuelmeurer Have you tried using `String.new(response)`? The difficulty here is that the existing design returns a string-like object that actually mixes in a great deal of additional functionality / objects to represent the full response.

**Comment by manuelmeurer** [comment]
Yeah, `String.new(response)` works fine! I'll use that, thanks!
