### ISSUE TITLE
response.cookies fails when using rest-client-components and rack-cache

### ISSUE THREAD

**Issue by darrenleeweber** [rest-client/rest-client#411]
The exception is
```
NoMethodError: undefined method `url' for #<RestClient::Rack::Compatibility:0x007fdc16559b10>
from /home/dlweber/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:52:in `block in cookie_jar'
```

e.g.

```ruby
> client = {:clientId=>"dms", :clientSecret=>"dms-annos"};
> tc.auth
=> #<RestClient::Resource:0x00000006018438
 @block=nil,
 @options={:cookies=>{}, :headers=>{:accept=>"application/ld+json", :content_type=>"application/ld+json"}, :open_timeout=>5, :read_timeout=>30},
 @url="https://triannon-dev.stanford.edu/auth">
> json_payloads = { accept: :json, content_type: :json };
> response = tc.auth["/client_identity"].post client.to_json, json_payloads;
> response.is_a? RestClient::Response
=> true
> response.headers
=> {:x_frame_options=>"SAMEORIGIN",
 :x_xss_protection=>"1; mode=block",
 :x_content_type_options=>"nosniff",
 :content_type=>"application/json; charset=utf-8",
 :etag=>"W/\"e9767a04a1db0d9b828970d126ab512d\"",
 :cache_control=>"max-age=0, private, must-revalidate",
 :x_request_id=>"7913b771-bfba-4870-871d-35d31224e959",
 :x_runtime=>"0.169223",
 :server=>"WEBrick/1.3.1 (Ruby/2.2.2/2015-04-13)",
 :date=>"Mon, 10 Aug 2015 18:37:24 GMT",
 :content_length=>"186",
 :connection=>"Keep-Alive",
 :set_cookie=>
  ["[\"request_method=POST; path=/\", \"_internal_session=QmFic2VmUEE5QTRoUTM1YzNaaXc4NVE1bVFaS3pOeS93VWtPYy9VWWF2b2tGcXlDRVZabUZzMEU5MisrdmVHS2RCR2JUK3FuZXNHWDZBbmtDR21xRUM0RldRYU1nd3pQTEQ3MUNUaVg5UDM4dVdnTy9LL2RSWTRaaFg2YitTMjNPRkpsZUpUY2ZCaFN3VkZkUkNEZWI5TUxDSzNYcUdNbTFJYWprSEdRdnFLVFcxKzFVc3BjTUtuU3QrbHFXS1N0cjV3ZllCVys5SWFjVFRjNUIvc0hlUHJiUUtHSU9qK096TXdUSk96NWJWNEJrSzQra2trakNSVjBHWmV4Ym1mWU15SFBYbmt5MURwT25Sc0VqYkswREd1WDB6K3IrS2Q2YlRuVXpiZk1IK3Rza0twSFRFWXIzWU41NkVZbWJWM0ZPRXZhajU1WklhUmkzeTlONUlPVEJ2QmsyRk5FTldiK3ljOGx6azJua0FNajJCc3I4YzVOZ09mUVVjckF1M255VHBTMU4yZ2owaE5ldzMzSnAzWFFzUHBCSnlZcXdPMlZHVTB3czVncFhyRXFIdDlhT3ZZUWhxWStoM2FVaTd3anhrUWJQRWQ4WWg5ZVRXcWQ0NnhlWXlZUnNvNHVWMjA0akJjQi83ZWhVSkU9LS0rWDEvRjFLbWFueks1SCt2WlNFcHBRPT0%3D--db491117968003865a0fa7679429f8e2fd9b282b; path=/; HttpOnly\"]"],
 :x_rack_cache=>"invalidate, pass"}

> response.cookies
NoMethodError: undefined method `url' for #<RestClient::Rack::Compatibility:0x007fdc16559b10>
from /home/dlweber/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:52:in `block in cookie_jar'

> response.request.class
=> RestClient::Rack::Compatibility
```

The gem bundle includes:
```
/home/snip/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.4
/home/snip/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-cache-1.2
/home/snip/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0
/home/snip/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rest-client-components-1.4.0
```

**Comment by darrenleeweber** [comment]
Adding a bit more debug info about the `response.request` instance that doesn't have a `url`,
```
#<RestClient::Rack::Compatibility:0x007f0f08720538
 @app=
  #<Rack::CommonLogger:0x007f0f08720588
   @app=
    #<Rack::Cache::Context:0x007f0f087209c0
     @backend=
      #<Proc:0x007f0f04c9d2f8@/home/dlweber/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rest-client-components-1.4.0/lib/restclient/components.rb:188>,
     @default_options=
      {"rack-cache.cache_key"=>Rack::Cache::Key,
       "rack-cache.verbose"=>false,
       "rack-cache.storage"=>
        #<Rack::Cache::Storage:0x007f0f04bfe590
         @entitystores=
          {"file:tmp/cache/anno_body"=>
            #<Rack::Cache::EntityStore::Disk:0x007f0f05823528
             @root="/data/src/dlss/ld4l_data/annotations/annotations2triannon/tmp/cache/anno_body">},
         @metastores=
          {"memcached://localhost:11211/anno_meta"=>
            #<Rack::Cache::MetaStore::Dalli:0x007f0f05823870
             @cache=
              #<Dalli::Client:0x007f0f058237f8
               @options={:namespace=>"anno_meta"},
               @ring=
                #<Dalli::Ring:0x007f0f058227b8
                 @continuum=nil,
                 @failover=true,
                 @servers=
                  [#<Dalli::Server:0x007f0f058229c0
                    @down_at=nil,
                    @error=nil,
                    @fail_count=0,
                    @hostname="localhost",
                    @inprogress=false,
                    @last_down_at=nil,
                    @lock=#<Monitor:0x007f0f05822740 @mon_count=0, @mon_mutex=#<Mutex:0x007f0f058226f0>, @mon_owner=nil>,
                    @msg=nil,
                    @options=
                     {:down_retry_delay=>1,
                      :socket_timeout=>0.5,
                      :socket_max_failures=>2,
                      :socket_failure_delay=>0.01,
                      :value_max_bytes=>1048576,
                      :compressor=>Dalli::Compressor,
                      :compression_min_size=>1024,
                      :compression_max_size=>false,
                      :serializer=>Marshal,
                      :username=>nil,
                      :password=>nil,
                      :keepalive=>true,
                      :namespace=>"anno_meta"},
                    @pid=8427,
                    @port=11211,
                    @sock=#<Dalli::Server::KSocket::TCP:fd 7>,
                    @socket_type=:tcp,
                    @version="1.4.14",
                    @weight=1>]>,
               @servers=["localhost:11211"]>>}>,
       "rack-cache.metastore"=>"memcached://localhost:11211/anno_meta",
       "rack-cache.entitystore"=>"file:tmp/cache/anno_body",
       "rack-cache.default_ttl"=>0,
       "rack-cache.ignore_headers"=>["Set-Cookie"],
       "rack-cache.private_headers"=>["Authorization", "Cookie"],
       "rack-cache.allow_reload"=>false,
       "rack-cache.allow_revalidate"=>false,
       "rack-cache.use_native_ttl"=>false},
     @env=nil,
     @private_header_keys=["HTTP_AUTHORIZATION", "HTTP_COOKIE"],
     @trace=[]>,
   @logger=#<IO:<STDOUT>>>>
```

**Comment by ab** [comment]
I'm not sure I understand all the context here. What is this `response.request` object an instance of? `RestClient::Rack::Compatibility`? What is that class, and where does it come from?

**Comment by darrenleeweber** [comment]
The context is in https://github.com/sul-dlss/triannon-client/blob/master/lib/triannon-client/triannon_client.rb#L60 with rack-cache enabled.  (The purpose of using rack-cache is primarily to cache json-ld context documents that might otherwise exceed HTTP request limits.)

**Comment by darrenleeweber** [comment]
WRT rest-client it looks like `request.response.url` is accessed while parsing cookies at:
  - https://github.com/rest-client/rest-client/blob/master/lib/restclient/abstract_response.rb#L63
  - Although the current master branch may not be the same as the 1.8.0 release.
Somehow, the rest-client-component replaces this instance of `@response` with an instance of `RestClient::Rack::Compatibility`.

**Comment by ab** [comment]
Got it, thanks. It doesn't really sound like it's a bug in rest-client, then.

**Comment by darrenleeweber** [comment]
Created linked issue:  https://github.com/crohr/rest-client-components/issues/10

**Comment by gkellogg** [comment]
As I recall, the problem in rest-client-component was that it was using a method internal to rest-client for which the method signature had changed. No bug in rest-client. I don't see the issue I reported anymore, and I'm not sure if this is the same issue.

**Comment by darrenleeweber** [comment]
All the discussion/documentation for this problem is here in this ticket, although it may have to be resolved in rest-client-component.  I'd rather keep it open here than try to transfer it all to the child project.
