### ISSUE TITLE
Failed to Install Gem on El Capitan

### ISSUE THREAD

**Issue by berniechiu** [rest-client/rest-client#425]
I used to successfully install `rest-client` at ease.

But after upgrading to El Capitan, the following message appears.

```shell
Installing unf_ext 0.0.7.1 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/berniechiu/.rbenv/versions/2.2.3/bin/ruby -r ./siteconf20151005-25697-101ll05.rb extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/berniechiu/.rbenv/versions/2.2.3/bin/$(RUBY_BASE_NAME)
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/Users/berniechiu/.rbenv/versions/2.2.3/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/berniechiu/.rbenv/versions/2.2.3/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
	from /Users/berniechiu/.rbenv/versions/2.2.3/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
	from /Users/berniechiu/.rbenv/versions/2.2.3/lib/ruby/2.2.0/mkmf.rb:735:in `try_func'
	from /Users/berniechiu/.rbenv/versions/2.2.3/lib/ruby/2.2.0/mkmf.rb:966:in `block in have_library'
	from /Users/berniechiu/.rbenv/versions/2.2.3/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
	from /Users/berniechiu/.rbenv/versions/2.2.3/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /Users/berniechiu/.rbenv/versions/2.2.3/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/berniechiu/.rbenv/versions/2.2.3/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
	from /Users/berniechiu/.rbenv/versions/2.2.3/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/berniechiu/.rbenv/versions/2.2.3/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
	from /Users/berniechiu/.rbenv/versions/2.2.3/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
	from /Users/berniechiu/.rbenv/versions/2.2.3/lib/ruby/2.2.0/mkmf.rb:961:in `have_library'
	from extconf.rb:6:in `<main>'

extconf failed, exit code 1

An error occurred while installing unf_ext (0.0.7.1), and Bundler cannot continue.
Make sure that `gem install unf_ext -v '0.0.7.1'` succeeds before bundling.
```

**Comment by berniechiu** [comment]
Reinstalling command line tools solved the problem.
