### ISSUE TITLE
throws an exception when ‘gzip’ content encoding return

### ISSUE THREAD

**Issue by vivian2011** [rest-client/rest-client#479]
when I get ‘gzip’ Content-Encoding in http response , it has an error.
 error stacktrace:
```
/home/anwenya/.rvm/gems/ruby-2.0.0-p643/gems/rest-client-1.8.0/lib/restclient/request.rb:504:in `read' 
/home/anwenya/.rvm/gems/ruby-2.0.0-p643/gems/rest-client-1.8.0/lib/restclient/request.rb:504:in `decode'
/home/anwenya/.rvm/gems/ruby-2.0.0-p643/gems/rest-client-1.8.0/lib/restclient/request.rb:489:in `process_result' 
/home/anwenya/.rvm/gems/ruby-2.0.0-p643/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit' 
/home/anwenya/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/net/http.rb:852:in `start'
/home/anwenya/.rvm/gems/ruby-2.0.0-p643/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
/home/anwenya/.rvm/gems/ruby-2.0.0-p643/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
/home/anwenya/.rvm/gems/ruby-2.0.0-p643/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
```

**Comment by vivian2011** [comment]
1、uninstall 
2、install
it's OK,   what's wrong?

**Comment by ab** [comment]
Can you provide more information on how to reproduce this error?

You are saying that if you uninstall and reinstall rest-client it works?
