### ISSUE TITLE
Restclient ffi_c loading error

### ISSUE THREAD

**Issue by Ekultek** [rest-client/rest-client#492]
Hi, today while I was attempting to require `rest-client` for an application I'm working on, I got the following error:

```
irb(main):001:0> require 'rest-client'
LoadError: cannot load such file -- ffi_c
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/ffi-1.9.10-x86-mingw32/lib/ffi.rb:6:in
 `rescue in <top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/ffi-1.9.10-x86-mingw32/lib/ffi.rb:3:in
 `<top (required)>'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0-x86-mingw32/lib/rest
client/windows/root_certs.rb:2:in `<top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0-x86-mingw32/lib/rest
client/windows.rb:7:in `require_relative'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0-x86-mingw32/lib/rest
client/windows.rb:7:in `<top (required)>'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0-x86-mingw32/lib/rest
client.rb:16:in `<top (required)>'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0-x86-mingw32/lib/rest
-client.rb:2:in `<top (required)>'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:13
3:in `require'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:13
3:in `rescue in require'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40
:in `require'
        from (irb):1
        from C:/Ruby23/bin/irb.cmd:19:in `<main>'
```

Is there a known workaround for this error?

**Comment by ab** [comment]
It looks like FFI may not yet work on Ruby 2.3.0 on Windows.

https://github.com/ffi/ffi/issues/500

**Comment by ab** [comment]
The upstream issue appears to be fixed, but feel free to reopen if not.
