### ISSUE TITLE
RestClient::InternalServerError - 500 Internal Server Error

### ISSUE THREAD

**Issue by gitrishi** [rest-client/rest-client#497]
I m getting internal server error when i hit the same url multiple times.. it works for first couple of times and then i see the exception - 

(puma stderr) 

```
2016-05-27 17:06:45 - RestClient::InternalServerError - 500 Internal Server Error:
        /home/.rvm/gems/ruby-2.1.1/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
        /home/.rvm/gems/ruby-2.1.1/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
        /home/.rvm/gems/ruby-2.1.1/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
        /home/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:853:in `start'
        /home/.rvm/gems/ruby-2.1.1/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
        /home/.rvm/gems/ruby-2.1.1/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
        /home/.rvm/gems/ruby-2.1.1/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
        /home/.rvm/gems/ruby-2.1.1/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'
        /home/myproj/lib/icinga_api.rb:32:in `get'
```

On the browser i see,
exception trace here ->>

```
# block; otherwise, it returns self.
    #
    def start  # :yield: http
      raise IOError, 'HTTP session already opened' if @started
      if block_given?
        begin
          do_start
          return yield(self)
        ensure
          do_finish
        end
      end
      do_start
      self
    end
```

What could be the issue here?

**Comment by gitrishi** [comment]
Looks like the issues is on application side, api  Closing the issue.
