### ISSUE TITLE
TypeError - "http" is not a class/module

### ISSUE THREAD

**Issue by ikhakoo** [rest-client/rest-client#537]
Receiving this error block when using stripe although the error resonates from rest-client. Has anyone had this issue? I've been searching to no avail and was hoping someone may know a resolution to this issue.

```
TypeError - "http" is not a class/module:
  rest-client (2.0.0) lib/restclient/request.rb:386:in `process_cookie_args!'
  rest-client (2.0.0) lib/restclient/request.rb:136:in `initialize'
  rest-client (2.0.0) lib/restclient/request.rb:52:in `execute'
   () Users/sump/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/stripe-ruby-7e17330561a2/lib/stripe.rb:344:in `execute_request'
   () Users/sump/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/stripe-ruby-7e17330561a2/lib/stripe.rb:230:in `execute_request_with_rescues'
   () Users/sump/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/stripe-ruby-7e17330561a2/lib/stripe.rb:182:in `request'
   () Users/sump/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/stripe-ruby-7e17330561a2/lib/stripe/api_operations/request.rb:15:in `request'
   () Users/sump/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/stripe-ruby-7e17330561a2/lib/stripe/api_operations/create.rb:5:in `create'
....
```

**Comment by ikhakoo** [comment]
I managed to figure out that this not related to rest-client and it was complications with other code in the application.

**Comment by pmsteil** [comment]
For my case I was getting this when I was trying to pass headers in as an array.  Co-pilot suggest I convert it to a hash like this:

```
headers_hash = {}
    headers.each do |header|
      headers_hash[header["header"]] = header["value"]
    end
```

and the api call went through, haven't validated my headers got there... :)
