### ISSUE TITLE
Response is nil instead of response object

### ISSUE THREAD

**Issue by ggrillone** [rest-client/rest-client#580]
I'm trying to make calls to external API and keep receiving `400 bad request` messages, so trying to figure out the response, but the response is always `nil` instead of a response object. Not sure why.

```
response = RestClient::Request.execute(
  method: :post,
  url: "MY_URL",
  user: "MY_USER",
  password: "MY_PASS",
  headers: {
    content_type: "application/json",
    accept: :json
  },
  payload: payload.to_json
)
# => RestClient::BadRequest: 400 Bad Request

response.code
#=> NoMethodError: undefined method `code' for nil:NilClass
```

Not sure if it's because I am using `execute` as opposed to calling the `post` method? 

UPDATE:

Using `post` seems to be resulting in a `nil` response as well:

```
response = RestClient.post "https://#{MY_USER}:#{MY_PASS}@whateverurl.com", payload, {content_type: :json, accept: :json}
#=> RestClient::BadRequest: 400 Bad Request

response.code
#=> NoMethodError: undefined method `code' for nil:NilClass
```

UPDATE 2:

Here's the trace in the console:

```
from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
  from /Users/myuser/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:853:in `start'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/rest-client-1.8.0/lib/restclient.rb:69:in `post'
  from (irb):9
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/railties-4.2.2/lib/rails/commands/console.rb:110:in `start'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/railties-4.2.2/lib/rails/commands/console.rb:9:in `start'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:68:in `console'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/railties-4.2.2/lib/rails/commands.rb:17:in `<top (required)>'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
  from /Users/myuser/Documents/pwnie_express/cloud_release_tool/release-manager-api/bin/rails:8:in `<top (required)>'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `block in load'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /Users/myuser/.rvm/gems/ruby-2.1.3/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
  from /Users/myuser/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /Users/myuser/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by ggrillone** [comment]
Looking at the code, if I'm understanding correctly, it appears if the response returns a 500, or unauthorized, or bad request it is not possible to see the response and just an exception is made?
https://github.com/rest-client/rest-client/blob/master/lib/restclient/abstract_response.rb#L102

So if code relies on reading an error code or error message, how can we can get from the response object?

**Comment by SpyMachine** [comment]
Have you tried catching your exception?
```
begin
...<your request>...
rescue RestClient::ExceptionWithResponse => e
   puts e.response
   end
```

**Comment by ab** [comment]
@ggrillone

As SpyMachine notes, you'll probably want to catch those exceptions in order to handle the response.

```ruby
begin
  RestClient.post('http://example.com', 'payload')
rescue RestClient::ExceptionWithResponse => err
  puts err.response
end
```

More background on what's going on with your variable ending up `nil`:

In ruby, if a statement containing an assignment raises an exception, then the left hand side of the assignment will remain unchanged, or it will be `nil` if it had no value before. This is similar to how a variable can be implicitly defined by a conditional.

```ruby
>> x
NameError: undefined local variable or method `x` for main:Object
>> if false
     x = 5
   end
>> x
=> nil
```

Notice how the x = 5 never actually executes, but it causes `x` to exist in local scope with value `nil`.

```ruby
>> x
NameError: undefined local variable or method `x` for main:Object
>> x = 1 / 0
ZeroDivisionError: divided by 0
>> x
=> nil # now defined, despite the exception
>> x = 3
=> 3
>> x = 1 / 0
ZeroDivisionError: divided by 0
>> x
=> 3 # unchanged
```

**Comment by Schwad** [comment]
@SpyMachine hello from 2019! Thanks for your answer - I think catching the exceptions explicitly is a flow that definitely works for our approach. Cheers :)
