### ISSUE TITLE
Getting IOError (not opened for reading) when sending a multipart request

### ISSUE THREAD

**Issue by halbano** [rest-client/rest-client#645]
Hello there, I'm having problems using a generic call with a method name using public_send. 

I am using a resource to point the API and cookies for authentication. I am building an API that communicates with another API. 
 
` @rest_client_instance = RestClient::Resource.new(ENV['GATEWAY_URL'], :cookies => resp.cookies)`
`response = @rest_client_instance[url].public_send(method, body, :headers => headers, :multipart => multipart)`

The body I am sending is: 

> Printing body: {:pk12=>#<File:/var/folders/0h/81d2k48s4wb25m9xwgkcp29w0000gn/T/RackMultipart20171122-19431-1fea1zy>, :srcStorePass=>"pepe", :srcAlias=>"123"}

Any help is really appreciated. 
Best Regards,
Hernán

**Comment by tute** [comment]
While trying to send a PDF file, I get:

```
9 TID-gskp3z61p WARN: IOError: closed stream
9 TID-gskp3z61p WARN: /usr/local/lib/ruby/2.5.0/delegate.rb:349:in `read'
/usr/local/lib/ruby/2.5.0/delegate.rb:349:in `block in delegating_block'
/opt/rails/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:163:in `create_file_field'
/opt/rails/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:137:in `block in build_stream'
/opt/rails/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `each'
/opt/rails/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `each_with_index'
/opt/rails/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `build_stream'
/opt/rails/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:47:in `initialize'
/opt/rails/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:16:in `new'
/opt/rails/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:16:in `generate'
/opt/rails/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:77:in `initialize'
/opt/rails/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `new'
/opt/rails/vendor/bundle/ruby/2.5.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
```

Not sure yet why.

**Comment by Adithya-copart** [comment]
I'm seeing this issue intermittently as well.

**Comment by KMontag42** [comment]
Any updates on this issue? I am seeing this as well.

**Comment by ab** [comment]
Is there a minimal reproducer for this issue?

**Comment by KronicDeth** [comment]
I'm getting this issue too, but can't reproduce it consistently.  I do seem to produce it more when doing integration tests that have the poll the remote API every few seconds.   I'm creating new Request objects for each polling though, so I'm not sure why that should matter unless there's some singleton or other global resource involved.

**Comment by Viktor-Ivliev** [comment]
I encountered a similar problem, but in my case, I had cached parameters, and at the repeated request - in fact, there were references to files that the client has already closed.
