### ISSUE TITLE
gem install rest-client fails with `Could not create Makefile`

### ISSUE THREAD

**Issue by belgoros** [rest-client/rest-client#651]
I tried to install the gem on `macOS Sierra, 10.12.6` and got the below error:
```
➜  ~ gem install rest-client
Building native extensions.  This could take a while...
ERROR:  Error installing rest-client:
	ERROR: Failed to build gem native extension.

    current directory: /Users/Serguei/.rvm/gems/ruby-2.4.0/gems/unf_ext-0.0.7.4/ext/unf_ext
/Users/Serguei/.rvm/rubies/ruby-2.4.0/bin/ruby -r ./siteconf20180103-9848-1id0gw8.rb extconf.rb
checking for -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/Serguei/.rvm/rubies/ruby-2.4.0/bin/$(RUBY_BASE_NAME)
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/Users/Serguei/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/Serguei/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:542:in `try_link0'
	from /Users/Serguei/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:557:in `try_link'
	from /Users/Serguei/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:775:in `try_func'
	from /Users/Serguei/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:1002:in `block in have_library'
	from /Users/Serguei/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
	from /Users/Serguei/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /Users/Serguei/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:321:in `open'
	from /Users/Serguei/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
	from /Users/Serguei/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:321:in `open'
	from /Users/Serguei/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
	from /Users/Serguei/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
	from /Users/Serguei/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/mkmf.rb:997:in `have_library'
	from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/Serguei/.rvm/gems/ruby-2.4.0/extensions/x86_64-darwin-16/2.4.0/unf_ext-0.0.7.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/Serguei/.rvm/gems/ruby-2.4.0/gems/unf_ext-0.0.7.4 for inspection.
Results logged to /Users/Serguei/.rvm/gems/ruby-2.4.0/extensions/x86_64-darwin-16/2.4.0/unf_ext-0.0.7.4/gem_make.out
```
As you could see, I'm using RVM to manage the gems. What's wrong with the installation ? Which option should I provide ? Thank you.

**Comment by belgoros** [comment]
Fixed it: Xcode was updated in the background and needed its license to be accepted (take a look inside the `mkmf.log`file). After starting XCode and accepting it, everything came back to normal.
