### ISSUE TITLE
"undefined method `code' for nil:NilClass" trying to inspect a result

### ISSUE THREAD

**Issue by henrik** [rest-client/rest-client#655]
When using https://github.com/ianfleeton/paypal-express in development to make a payment using PayPal's sandbox API, I noticed that attempting to log the response will cause a NoMethodError, "undefined method `code' for nil:NilClass".

The backtrace contains

> …/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:16:in `code'
…/gems/rest-client-2.0.2/lib/restclient/response.rb:38:in `inspect'
> app/models/pay_pal_api.rb:44:in `inspect'

It seems to come down to `AbstractReponse#code` doing `@net_http_res.code.to_i` when `@net_http_res` is nil.

We probably don't want `inspect` to ever raise an exception.

The obvious fix is to check for nils, but maybe there's some deeper issue here, causing a value to be nil when it shouldn't? I haven't delved deep enough into either rest-client or paypal-express to know for sure. I'll mention @ianfleeton of paypal-express in case he has any insight.

**Comment by ianfleeton** [comment]
I don't think paypal-express is interfering.

I'm not familiar with rest-client but if the nil in the response is invalid then it looks like `Request` needs to handle `Net::HTTP#request` returning nil. I'm not sure how or why `Net::HTTP#request` returns nil from reading the ruby source -- can you check it actually does as my tracing is through reading the code not running it and I might have messed up.

`Response.create` initialises `@net_http_res` (via `AbstractResponse#response_set_vars`) on a new `Response`

`Request#process_result` calls `Response.create` with nil res (as only creation of a Response)

`res` comes from `Request#net_http_do_request` which receives `http` (a `Net::HTTP`?), calls `#request` on it which returns nil, which it in turn returns.

`http` comes from `net.start |http|` within `Request#transmit`, and `net` is a `Net::HTTP`

**Comment by henrik** [comment]
Thank you, @ianfleeton. I'll try to take some time to trace where the nil comes from specifically.

**Comment by grillermo** [comment]
@henrik Did you found anything? i'm having the same problem with paypal after updating to 2.0.2

**Comment by henrik** [comment]
Hi Guillermo,

This fixed it for me: https://github.com/nov/paypal-express/issues/99#comment-266486060

**Comment by henrik** [comment]
That is, the underlying issue. I have not spent any more time digging into the logging issue, sorry!

**Comment by ab** [comment]
Do y'all have a minimal reproducer here? It sounds like there is a rest-client bug involved, but I don't understand how we could have ended up with a `nil` `@net_http_res`, since that is always supposed to be a `Net::HTTPResponse` object.

**Comment by henrik** [comment]
Sorry, don't have this context any more, but if I see the issue again I'll try.

**Comment by CodingAnarchy** [comment]
I've run into this same issue on a JRuby 9.2.8 application (MRI 2.5.3 syntax) using a straight `RestClient.get` on a standard URL inside a Kubernetes cluster.  It was working with JRuby 9.1.17 (MRI 2.3.3 syntax) and RestClient 1.8, but failed when I updated to JRuby 9.2.8 and RestClient 2.1.

It doesn't appear that JRuby is part of the issue, but I hope this helps.

**Comment by CodingAnarchy** [comment]
Further info, if helpful.  Downgrading to RC 1.8 resolved the issue for my JRuby case.  I also do not see this issue on my Rails application that is running MRI 2.6.3, if that helps narrow things down.

**Comment by ab** [comment]
Thanks. What would really help here is a minimal reliable reproducer.

**Comment by chriscz** [comment]
Hi everyone,

I have also come across this bug and I've traced it to the `RestClient::Response.create` class. 
This is where my debugger triggered the error as it assumed it could inspect the variable right after creation. 

The problem seems to be in the `RestClient::Request::create` class method which results in a string being created that 's inconsistent  before `response_set_vars` gets called (`net_http_res` is `nil`). It could very well be that somewhere in the runtime string creation is being monitored for some reason.

The simplest alternative is updating the inspect method, but maybe the workaround below could work? I'm not sure about its compatibility. I've tested it on my local machine, however it breaks again in production and I'm not sure why.

Here's the original `RestClient::Response.create` (at least in version 2.1.0)
```ruby
def self.create(body, net_http_res, request, start_time=nil)
  result = self.new(body || '')

  result.response_set_vars(net_http_res, request, start_time)
  fix_encoding(result)

  result
end
```

Here's my suggested monkey patch (tested on MRI 2.5.7)
```ruby
require 'restclient/response'

module RestClient
  class Response
    # Idea taken from Steve Klabnik
    # - https://words.steveklabnik.com/beware-subclassing-ruby-core-classes
    alias_method :string_initialize, :initialize

    def initialize(body, net_http_res, request, start_time)
      response_set_vars(net_http_res, request, start_time)
      string_initialize(body)
    end

    def self.create(body, net_http_res, request, start_time = nil)
      result = self.new(body || '', net_http_res, request, start_time)
      fix_encoding(result)
      result
    end

  end
end
```

**Comment by hlascelles** [comment]
We have run into this too recently. I have written up the exact code flow below. You should be able to just copy-n-paste run this for a complete demo:

```ruby
require "rest-client"

response = RestClient.get("www.google.com")

# I can inspect this object I have now:
puts response.inspect
# => <RestClient::Response 200 "<!doctype h...">

# Is this a String? Great! I can pass it around my codebase.
puts response.is_a?(String)
# => true

# That means I can encode it before saving it somewhere (sound of distant alarm bells)
encoded_response = response.encode(Encoding::UTF_8)

# Is this still *actually really* a RestClient::Response?
puts encoded_response.class == RestClient::Response
# => true

# Now, I'll put this "String" in S3 by using the AWS S3 gem which likes to log strings by "inspecting" them:
# https://github.com/aws/aws-sdk-ruby/blob/version-3/gems/aws-sdk-core/lib/aws-sdk-core/log/param_formatter.rb#L43
# (Simplified to the line below)
encoded_response.inspect

# Bang!
# undefined method `code' for nil:NilClass
# restclient/abstract_response.rb:16:in `code'
# restclient/response.rb:38:in `inspect'

```

So the problem for us was that `encode(Encoding::UTF_8)` appeared to do the right thing, but it actually wiped the instance variables by creating a new `RestClient::Response` object.

**Comment by obulkin** [comment]
Seeing this issue with a call to `each_line` as well. The resulting `RestClient::Response` objects for each line no longer have the right internals to respond correctly to `inspect`.
