### ISSUE TITLE
Can't use proxy password with percent encoded characters

### ISSUE THREAD

**Issue by jhernand** [rest-client/rest-client#661]
[RFC 3986](https://tools.ietf.org/html/rfc3986#section-2.2) defines a set of _reserved_ characters that can't appear directly in URL components like the _userinfo_. It also defines the _percent encoding_ mechanism to escape them when needed. That means that an URI containing characters like `$` or `?` in the userinfo need to be encoded. For example, if the user is `myuser` and the password is `$?xxxx` then the proxy URI should be like this:

```
http://myuser:%24%3Fxxxx@myproxy.example.com:3128
```

The Ruby `URI.parse` methods accepts this syntax, but it doesn't do the corresponding decoding. The program that uses this URI needs to do the decoding explicitly before using it:

```ruby
require 'cgi'
require 'uri'

uri = URI.parse('http://myuser:%24%3Fxxxx@myproxy.example.com:3128')
password = CGI.unescape(uri.password)
...
```

But apparently, for proxy URIs, `rest-client` uses directly the value returned by the `password` method:

https://github.com/rest-client/rest-client/blob/f450a0f086f1cd1049abbef2a2c66166a1a9ba71/lib/restclient/request.rb#L453-L454

As a result when the password contain percent encoded characters `rest-client` uses a wrong proxy password, and the proxy authentication fails.

Using the password directly, without percent encoding isn't an option, because `URI.parse` throws an exception:

```
irb(main):001:0> URI.parse('http://myuser:$?xxxx@myproxy.com:3128')
URI::InvalidURIError: bad URI(is not URI?): http://myuser:$?xxxx@myproxy.com:3128
	from /files/rbenv/versions/2.4.1/lib/ruby/2.4.0/uri/rfc3986_parser.rb:67:in `split'
	from /files/rbenv/versions/2.4.1/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'
	from /files/rbenv/versions/2.4.1/lib/ruby/2.4.0/uri/common.rb:231:in `parse'
	from (irb):6
	from /files/rbenv/versions/2.4.1/bin/irb:11:in `<main>'
```

**Comment by cben** [comment]
I believe the same also applies to percent-encoded username.
RFC doesn't talk of password specifically; AFAICT it says percent encoding applies to any component, and syntax for whole whole userinfo field clearly shows percent encoding is applicable:
```
userinfo    = *( unreserved / pct-encoded / sub-delims / ":" )
```
username encoding does happen in the wild for example when using email as username <https://stackoverflow.com/questions/10050877/url-username-with>.

**Comment by moolitayer** [comment]
AFAIK rest-client seems to escape the target URL user and password but not the proxy user and password:
https://github.com/rest-client/rest-client/blob/c2e11b943a8514a94a2b7e68cb0f213cef06a6cc/lib/restclient/request.rb#L607
https://github.com/rest-client/rest-client/blob/c2e11b943a8514a94a2b7e68cb0f213cef06a6cc/lib/restclient/request.rb#L428
https://github.com/rest-client/rest-client/blob/c2e11b943a8514a94a2b7e68cb0f213cef06a6cc/lib/restclient/request.rb#L78
