### ISSUE TITLE
undefined method `code' for nil:NilClass (NoMethodError) in Ruby 2.4 and 2.5

### ISSUE THREAD

**Issue by JunichiIto** [rest-client/rest-client#662]
I have a code like this:

```ruby
require 'rest-client'
require 'vcr'

require 'webmock'
include WebMock::API

WebMock.enable!

VCR.configure do |config|
  config.cassette_library_dir = "fixtures"
  config.hook_into :webmock
end

VCR.use_cassette 'response' do
  response = RestClient.post 'https://example.com/foo', {}
  hash = CGI.parse(response)
  puts "baz: #{hash['baz']}"
end
```

This is Gemfile:

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rest-client', '2.0.2'
gem "webmock", '3.4.1', require: false
gem "vcr", '4.0.0', require: false
```

I could run it in Ruby 2.3.6:

```
$ ruby -v
ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-darwin17]
$ bundle exec ruby ./sample.rb
baz: ["0"]
```

However, it fails in Ruby 2.4 and 2.5 with ``undefined method `code' for nil:NilClass (NoMethodError)``:

```
$ ruby -v
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]
$ bundle exec ruby ./sample.rb
/Users/jit/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:16:in `code': undefined method `code' for nil:NilClass (NoMethodError)
	from /Users/jit/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/response.rb:38:in `inspect'
	from ./sample.rb:17:in `inspect'
	from ./sample.rb:17:in `block in <main>'
	from /Users/jit/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/vcr-4.0.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
	from /Users/jit/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/vcr-4.0.0/lib/vcr.rb:188:in `use_cassette'
	from ./sample.rb:14:in `<main>'
```

```
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
$ bundle exec ruby ./sample.rb
Traceback (most recent call last):
	6: from ./sample.rb:14:in `<main>'
	5: from /Users/jit/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/vcr-4.0.0/lib/vcr.rb:188:in `use_cassette'
	4: from /Users/jit/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/vcr-4.0.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
	3: from ./sample.rb:17:in `block in <main>'
	2: from ./sample.rb:17:in `inspect'
	1: from /Users/jit/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/response.rb:38:in `inspect'
/Users/jit/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:16:in `code': undefined method `code' for nil:NilClass (NoMethodError)
```

Here is a sample app to reproduce this issue:

https://github.com/JunichiIto/rest-client-sandbox

I investigated as far as I can, but I could not find the cause. Could you solve this issue, please?

**Comment by JunichiIto** [comment]
I found a workaround. Passing copied string to `CGI.parse` can avoid this issue:

```diff
-  hash = CGI.parse(response)
+  hash = CGI.parse(response.to_s)
```

But I don't know why...

**Comment by JunichiIto** [comment]
I found the cause of this issue. `CGI.unescape` is used in `CGI.parse` and its behavior has changed:

```
$ ruby -v -rcgi/util -e 'class S < String; end; puts CGI.unescape(S.new("a")).class'

ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-darwin17]
String

$ ruby -v -rcgi/util -e 'class S < String; end; puts CGI.unescape(S.new("a")).class'

ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]
S
```

I submitted an issue to ruby-lang:

[Bug \#14732: CGI\.unescape returns different instance between Ruby 2\.3 and 2\.4 \- Ruby trunk \- Ruby Issue Tracking System](https://bugs.ruby-lang.org/issues/14732)

I close this issue because rest-client is not the cause. Thank you.
