### ISSUE TITLE
undefined method `code' for #<String:0x2e468c0> at rest-client-2.1.0/lib/restclient/exceptions.rb:123:in `http_code'

### ISSUE THREAD

**Issue by rc-jprior** [rest-client/rest-client#829]
I have not traced down exactly what triggered this, but we're seeing problems getting exception messages out of restclient exceptions.

/app/vendor/bundle/jruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/exceptions.rb:123:in `http_code'
/app/vendor/bundle/jruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/exceptions.rb:179:in `block in default_message'
/app/vendor/bundle/jruby/2.6.0/gems/rest-client-2.1.0/lib/restclient/exceptions.rb:142:in `message'

Where the calling code looks something like this:

```
rescue StandardError => e
        log.error "Failed to read\n#{e.message}\n#{e.backtrace.join("\n")}" # This is the line that raises the exception, e.message
        read_failures.increment
        raise ReadFailure, e.message
```

For now we're deploying a fix rescue when calling `e.message` and return a more generic message, but apparently it is possible for rest client exceptions to be a string instead of a response with a code.

**Comment by edallen** [comment]
I see this exception when the server I am making the request to is down and needs to be restarted.
